"""add site_id to user table

Revision ID: 021d61021620
Revises: be2e31fb919e
Create Date: 2017-08-02 22:31:27.734455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021d61021620'
down_revision = 'be2e31fb919e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_user', sa.Column('site_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_user', 'site_id')
    # ### end Alembic commands ###
