"""update post user

Revision ID: 04a547d6ad05
Revises: a9f47241f10c
Create Date: 2017-03-30 13:04:29.205365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a547d6ad05'
down_revision = 'a9f47241f10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'body')
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
