"""add store_seo table

Revision ID: 0d5f8327248e
Revises: 7a5e1e3486bd
Create Date: 2017-07-27 22:29:36.714341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d5f8327248e'
down_revision = '7a5e1e3486bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('visit_url', sa.String(length=100), nullable=False),
    sa.Column('site_domain', sa.String(length=100), nullable=True),
    sa.Column('favicon', sa.String(length=100), nullable=True),
    sa.Column('pricing', sa.SmallInteger(), nullable=True),
    sa.Column('locale', sa.String(length=4), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('domain', sa.SmallInteger(), nullable=True),
    sa.Column('copyright', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unicode', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain'),
    sa.UniqueConstraint('visit_url')
    )
    op.create_index(op.f('ix_fp_store_master_uid'), 'fp_store', ['master_uid'], unique=False)
    op.create_index(op.f('ix_fp_store_name'), 'fp_store', ['name'], unique=True)
    op.create_table('fp_store_seo',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['fp_language.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['fp_store.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'language_id')
    )
    op.drop_table('fp_stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_stores',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('locale', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('domain', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('fp_store_seo')
    op.drop_index(op.f('ix_fp_store_name'), table_name='fp_store')
    op.drop_index(op.f('ix_fp_store_master_uid'), table_name='fp_store')
    op.drop_table('fp_store')
    # ### end Alembic commands ###
