"""add asset

Revision ID: 1a85f9645db7
Revises: 4d2a8e80b9a6
Create Date: 2017-05-23 19:53:39.173100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a85f9645db7'
down_revision = '4d2a8e80b9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('top', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fp_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['fp_directory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.add_column('fp_category', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('fp_category', sa.Column('top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_category', 'top')
    op.drop_column('fp_category', 'sort_order')
    op.drop_table('fp_asset')
    op.drop_table('fp_directory')
    # ### end Alembic commands ###
