"""add site_id to category and banner table

Revision ID: 48da0c61e109
Revises: 8b053cc8ad10
Create Date: 2017-08-03 10:33:24.101650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48da0c61e109'
down_revision = '8b053cc8ad10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_banner', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_banner', 'fp_site', ['site_id'], ['id'])
    op.add_column('fp_category', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_category', 'fp_site', ['site_id'], ['id'])
    op.add_column('fp_tag', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_tag', 'fp_site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fp_tag', type_='foreignkey')
    op.drop_column('fp_tag', 'site_id')
    op.drop_constraint(None, 'fp_category', type_='foreignkey')
    op.drop_column('fp_category', 'site_id')
    op.drop_constraint(None, 'fp_banner', type_='foreignkey')
    op.drop_column('fp_banner', 'site_id')
    # ### end Alembic commands ###
