"""init database

Revision ID: 4d2a8e80b9a6
Revises: 
Create Date: 2017-05-18 20:00:44.359049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2a8e80b9a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fp_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('group', 'store'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_category_name'), 'fp_category', ['name'], unique=True)
    op.create_table('fp_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('time_limit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('fp_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fp_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('sim_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_tag_name'), 'fp_tag', ['name'], unique=True)
    op.create_table('fp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('language', sa.String(length=4), nullable=True),
    sa.Column('time_zone', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.Column('disabled_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_user_email'), 'fp_user', ['email'], unique=True)
    op.create_index(op.f('ix_fp_user_username'), 'fp_user', ['username'], unique=True)
    op.create_table('fp_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('line_one', sa.String(length=100), nullable=True),
    sa.Column('line_two', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name_contact', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['fp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fp_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('features', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('banner', sa.String(length=100), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sort_num', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('recommend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['fp_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_brand_created_at'), 'fp_brand', ['created_at'], unique=False)
    op.create_index(op.f('ix_fp_brand_name'), 'fp_brand', ['name'], unique=True)
    op.create_table('fp_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['fp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_post_created_at'), 'fp_post', ['created_at'], unique=False)
    op.create_table('fp_role_ability',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['fp_ability.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['fp_role.id'], )
    )
    op.create_table('fp_user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['fp_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fp_user.id'], )
    )
    op.create_table('fp_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rid', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('pay_money', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('total_money', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('discount_money', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('gift_money', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('freight', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('status', sa.Enum('cancelled', 'closed', 'open', 'pending', 'paid', 'sent', 'received'), nullable=True),
    sa.Column('payed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('from_site', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['fp_address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_order_rid'), 'fp_order', ['rid'], unique=True)
    op.create_table('fp_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rid', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('discount_price', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('bar_code', sa.String(length=64), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('low_stock', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('item', 'free_product', 'gift_card', 'software', 'key', name='producttypeenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('rate_val', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('rate_count', sa.Integer(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('comment_stars', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('recommend', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['fp_brand.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_product_rid'), 'fp_product', ['rid'], unique=True)
    op.create_table('fp_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('rate_comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['fp_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['fp_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fp_product_category',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fp_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['fp_product.id'], )
    )
    op.create_table('fp_product_tag',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['fp_product.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['fp_tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fp_product_tag')
    op.drop_table('fp_product_category')
    op.drop_table('fp_order_detail')
    op.drop_index(op.f('ix_fp_product_rid'), table_name='fp_product')
    op.drop_table('fp_product')
    op.drop_index(op.f('ix_fp_order_rid'), table_name='fp_order')
    op.drop_table('fp_order')
    op.drop_table('fp_user_role')
    op.drop_table('fp_role_ability')
    op.drop_index(op.f('ix_fp_post_created_at'), table_name='fp_post')
    op.drop_table('fp_post')
    op.drop_index(op.f('ix_fp_brand_name'), table_name='fp_brand')
    op.drop_index(op.f('ix_fp_brand_created_at'), table_name='fp_brand')
    op.drop_table('fp_brand')
    op.drop_table('fp_address')
    op.drop_index(op.f('ix_fp_user_username'), table_name='fp_user')
    op.drop_index(op.f('ix_fp_user_email'), table_name='fp_user')
    op.drop_table('fp_user')
    op.drop_index(op.f('ix_fp_tag_name'), table_name='fp_tag')
    op.drop_table('fp_tag')
    op.drop_table('fp_role')
    op.drop_table('fp_company')
    op.drop_index(op.f('ix_fp_category_name'), table_name='fp_category')
    op.drop_table('fp_category')
    op.drop_table('fp_ability')
    # ### end Alembic commands ###
