"""add product image sku table

Revision ID: 56601a4e3f90
Revises: 62224c618f81
Create Date: 2017-08-06 10:34:05.680366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56601a4e3f90'
down_revision = '62224c618f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['fp_asset.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['fp_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fp_product_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('serial_no', sa.String(length=12), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('s_model', sa.String(length=64), nullable=False),
    sa.Column('s_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('outside_serial_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cover_id'], ['fp_asset.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['fp_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fp_product_sku_created_at'), 'fp_product_sku', ['created_at'], unique=False)
    op.create_index(op.f('ix_fp_product_sku_master_uid'), 'fp_product_sku', ['master_uid'], unique=False)
    op.create_index(op.f('ix_fp_product_sku_outside_serial_no'), 'fp_product_sku', ['outside_serial_no'], unique=False)
    op.create_index(op.f('ix_fp_product_sku_serial_no'), 'fp_product_sku', ['serial_no'], unique=True)
    op.drop_column('fp_product', 'model')
    op.drop_column('fp_product', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('type', mysql.ENUM('item', 'free_product', 'gift_card', 'software', 'key'), nullable=True))
    op.add_column('fp_product', sa.Column('model', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_fp_product_sku_serial_no'), table_name='fp_product_sku')
    op.drop_index(op.f('ix_fp_product_sku_outside_serial_no'), table_name='fp_product_sku')
    op.drop_index(op.f('ix_fp_product_sku_master_uid'), table_name='fp_product_sku')
    op.drop_index(op.f('ix_fp_product_sku_created_at'), table_name='fp_product_sku')
    op.drop_table('fp_product_sku')
    op.drop_table('fp_product_image')
    # ### end Alembic commands ###
