"""add xid for user table

Revision ID: 5d3e50b256a8
Revises: 5dafe73dbe76
Create Date: 2017-08-02 16:26:35.406181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3e50b256a8'
down_revision = '5dafe73dbe76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_user', sa.Column('xid', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_fp_user_xid'), 'fp_user', ['xid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fp_user_xid'), table_name='fp_user')
    op.drop_column('fp_user', 'xid')
    # ### end Alembic commands ###
