"""add counter table

Revision ID: 5dafe73dbe76
Revises: 955dcfa369f3
Create Date: 2017-08-02 15:12:45.564907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dafe73dbe76'
down_revision = '955dcfa369f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fp_counter')
    # ### end Alembic commands ###
