"""modify brand logo/banner

Revision ID: 5df72bf7d9fa
Revises: b6931f3df865
Create Date: 2017-05-27 13:16:36.156046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5df72bf7d9fa'
down_revision = 'b6931f3df865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('banner_id', sa.Integer(), nullable=True))
    op.add_column('fp_brand', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.drop_constraint('fp_brand_ibfk_3', 'fp_brand', type_='foreignkey')
    op.drop_constraint('fp_brand_ibfk_2', 'fp_brand', type_='foreignkey')
    op.drop_column('fp_brand', 'logo')
    op.drop_column('fp_brand', 'banner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('banner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('fp_brand', sa.Column('logo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('fp_brand_ibfk_2', 'fp_brand', 'fp_asset', ['banner'], ['id'])
    op.create_foreign_key('fp_brand_ibfk_3', 'fp_brand', 'fp_asset', ['logo'], ['id'])
    op.drop_column('fp_brand', 'logo_id')
    op.drop_column('fp_brand', 'banner_id')
    # ### end Alembic commands ###
