"""modify language image

Revision ID: 5f92a678689b
Revises: c9b4676adb67
Create Date: 2017-05-29 23:38:19.163800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f92a678689b'
down_revision = 'c9b4676adb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('locale', sa.String(length=255), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('directory', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_fp_language_name'), 'fp_language', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fp_language_name'), table_name='fp_language')
    op.drop_table('fp_language')
    # ### end Alembic commands ###
