"""update site table

Revision ID: 62224c618f81
Revises: 8c5ccaec30ab
Create Date: 2017-08-04 11:27:05.215242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62224c618f81'
down_revision = '8c5ccaec30ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_site_country',
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['fp_country.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['fp_site.id'], )
    )
    op.add_column('fp_site', sa.Column('default_country', sa.Integer(), nullable=True))
    op.add_column('fp_site', sa.Column('default_currency', sa.Integer(), nullable=True))
    op.add_column('fp_site', sa.Column('default_language', sa.Integer(), nullable=True))
    op.drop_column('fp_site', 'currency')
    op.drop_column('fp_site', 'locale')
    op.drop_column('fp_site', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_site', sa.Column('country', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('fp_site', sa.Column('locale', mysql.VARCHAR(length=4), nullable=True))
    op.add_column('fp_site', sa.Column('currency', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('fp_site', 'default_language')
    op.drop_column('fp_site', 'default_currency')
    op.drop_column('fp_site', 'default_country')
    op.drop_table('fp_site_country')
    # ### end Alembic commands ###
