"""add is_default asset table

Revision ID: 67a809da38fc
Revises: aaa4a74ab32d
Create Date: 2017-08-06 21:56:25.175290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a809da38fc'
down_revision = 'aaa4a74ab32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_asset', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('fp_directory', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_directory', 'is_default')
    op.drop_column('fp_asset', 'is_default')
    # ### end Alembic commands ###
