"""modify store to site table

Revision ID: 7a3fb1b214b5
Revises: 5d3e50b256a8
Create Date: 2017-08-02 21:29:01.066888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a3fb1b214b5'
down_revision = '5d3e50b256a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_uid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('serial_no', sa.String(length=32), nullable=False),
    sa.Column('visit_url', sa.String(length=100), nullable=False),
    sa.Column('site_domain', sa.String(length=100), nullable=True),
    sa.Column('favicon', sa.String(length=100), nullable=True),
    sa.Column('pricing', sa.SmallInteger(), nullable=True),
    sa.Column('locale', sa.String(length=4), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('domain', sa.SmallInteger(), nullable=True),
    sa.Column('copyright', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unicode', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_domain'),
    sa.UniqueConstraint('visit_url')
    )
    op.create_index(op.f('ix_fp_site_master_uid'), 'fp_site', ['master_uid'], unique=False)
    op.create_index(op.f('ix_fp_site_name'), 'fp_site', ['name'], unique=True)
    op.create_index(op.f('ix_fp_site_serial_no'), 'fp_site', ['serial_no'], unique=True)
    op.create_table('fp_site_seo',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['fp_language.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['fp_site.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'language_id')
    )
    op.drop_table('fp_store_seo')
    op.drop_table('fp_store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_store',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('master_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('visit_url', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('site_domain', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('favicon', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pricing', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('locale', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('domain', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('copyright', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('unicode', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('serial_no', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('fp_store_seo',
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('language_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['fp_language.id'], name='fp_store_seo_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['fp_store.id'], name='fp_store_seo_ibfk_2'),
    sa.PrimaryKeyConstraint('store_id', 'language_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('fp_site_seo')
    op.drop_index(op.f('ix_fp_site_serial_no'), table_name='fp_site')
    op.drop_index(op.f('ix_fp_site_name'), table_name='fp_site')
    op.drop_index(op.f('ix_fp_site_master_uid'), table_name='fp_site')
    op.drop_table('fp_site')
    # ### end Alembic commands ###
