"""add is_setting for user table

Revision ID: 7a5e1e3486bd
Revises: 59d742f6963a
Create Date: 2017-07-27 17:07:31.232178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5e1e3486bd'
down_revision = '59d742f6963a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_user', sa.Column('is_setting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_user', 'is_setting')
    # ### end Alembic commands ###
