"""modify brand logo/banner

Revision ID: 8229f18658d8
Revises: 291e66afb589
Create Date: 2017-05-27 10:59:10.005174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8229f18658d8'
down_revision = '291e66afb589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('banner_id', sa.Integer(), nullable=True))
    op.add_column('fp_brand', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_brand', 'fp_asset', ['logo_id'], ['id'])
    op.create_foreign_key(None, 'fp_brand', 'fp_asset', ['banner_id'], ['id'])
    op.drop_column('fp_brand', 'banner')
    op.drop_column('fp_brand', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('logo', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('fp_brand', sa.Column('banner', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'fp_brand', type_='foreignkey')
    op.drop_constraint(None, 'fp_brand', type_='foreignkey')
    op.drop_column('fp_brand', 'logo_id')
    op.drop_column('fp_brand', 'banner_id')
    # ### end Alembic commands ###
