"""update field product table

Revision ID: 8633a40491b2
Revises: ddddc91d3323
Create Date: 2017-08-03 17:39:37.050463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8633a40491b2'
down_revision = 'ddddc91d3323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('is_recommend', sa.Boolean(), nullable=True))
    op.add_column('fp_product', sa.Column('is_shipping', sa.Boolean(), nullable=True))
    op.add_column('fp_product', sa.Column('is_subtract', sa.Boolean(), nullable=True))
    op.add_column('fp_product', sa.Column('lowest_stock', sa.Integer(), nullable=True))
    op.add_column('fp_product', sa.Column('mini_quantity', sa.Integer(), nullable=True))
    op.drop_column('fp_product', 'subtract')
    op.drop_column('fp_product', 'recommend')
    op.drop_column('fp_product', 'shipping')
    op.drop_column('fp_product', 'mini_cnt')
    op.drop_column('fp_product', 'low_stock')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('low_stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('fp_product', sa.Column('mini_cnt', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('fp_product', sa.Column('shipping', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('fp_product', sa.Column('recommend', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('fp_product', sa.Column('subtract', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('fp_product', 'mini_quantity')
    op.drop_column('fp_product', 'lowest_stock')
    op.drop_column('fp_product', 'is_subtract')
    op.drop_column('fp_product', 'is_shipping')
    op.drop_column('fp_product', 'is_recommend')
    # ### end Alembic commands ###
