"""add site_id to directory and asset table

Revision ID: 8b053cc8ad10
Revises: 021d61021620
Create Date: 2017-08-02 23:30:10.244718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b053cc8ad10'
down_revision = '021d61021620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_asset', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fp_asset_site_id'), 'fp_asset', ['site_id'], unique=False)
    op.add_column('fp_directory', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fp_directory_site_id'), 'fp_directory', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fp_directory_site_id'), table_name='fp_directory')
    op.drop_column('fp_directory', 'site_id')
    op.drop_index(op.f('ix_fp_asset_site_id'), table_name='fp_asset')
    op.drop_column('fp_asset', 'site_id')
    # ### end Alembic commands ###
