"""add length/weight/zone/geozone table

Revision ID: 9398e136736e
Revises: 2b8d132e5aee
Create Date: 2017-06-08 11:27:16.899281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9398e136736e'
down_revision = '2b8d132e5aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_geo_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fp_length_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(precision=15, asdecimal=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fp_length_class_description',
    sa.Column('length_class_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['fp_language.id'], ),
    sa.ForeignKeyConstraint(['length_class_id'], ['fp_length_class.id'], ),
    sa.PrimaryKeyConstraint('length_class_id', 'language_id')
    )
    op.create_table('fp_zone_geo_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('geo_zone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['fp_country.id'], ),
    sa.ForeignKeyConstraint(['geo_zone_id'], ['fp_geo_zone.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['fp_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fp_zone_geo_zone')
    op.drop_table('fp_length_class_description')
    op.drop_table('fp_length_class')
    op.drop_table('fp_geo_zone')
    # ### end Alembic commands ###
