"""add create_update_at product table

Revision ID: a7893e4dd6ae
Revises: 4c8dac463381
Create Date: 2017-08-03 23:42:55.393437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7893e4dd6ae'
down_revision = '4c8dac463381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('fp_product', sa.Column('published_at', sa.Integer(), nullable=True))
    op.add_column('fp_product', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_product', 'updated_at')
    op.drop_column('fp_product', 'published_at')
    op.drop_column('fp_product', 'created_at')
    # ### end Alembic commands ###
