"""add serial_no product_sku table

Revision ID: aaa4a74ab32d
Revises: 38e42823f418
Create Date: 2017-08-06 21:41:56.014656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa4a74ab32d'
down_revision = '38e42823f418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fp_product', 'sku',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.create_foreign_key(None, 'fp_product', 'fp_asset', ['cover_id'], ['id'])
    op.add_column('fp_product_sku', sa.Column('product_serial_no', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_product_sku', 'product_serial_no')
    op.drop_constraint(None, 'fp_product', type_='foreignkey')
    op.alter_column('fp_product', 'sku',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
