"""modify brand logo/banner

Revision ID: b6931f3df865
Revises: e5a272aaa07c
Create Date: 2017-05-27 11:36:44.648862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6931f3df865'
down_revision = 'e5a272aaa07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('logo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_brand', 'fp_asset', ['logo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fp_brand', type_='foreignkey')
    op.drop_column('fp_brand', 'logo')
    # ### end Alembic commands ###
