"""modify recommended to brand table

Revision ID: be2e31fb919e
Revises: c26f0e3434ae
Create Date: 2017-08-02 22:26:29.808788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be2e31fb919e'
down_revision = 'c26f0e3434ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('is_recommended', sa.Boolean(), nullable=True))
    op.drop_column('fp_brand', 'recommend')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('recommend', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('fp_brand', 'is_recommended')
    # ### end Alembic commands ###
