"""add type product table

Revision ID: c237dc79f0b4
Revises: 56601a4e3f90
Create Date: 2017-08-06 11:22:59.697468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c237dc79f0b4'
down_revision = '56601a4e3f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_product', 'type')
    # ### end Alembic commands ###
