"""add site_id to brand table

Revision ID: c26f0e3434ae
Revises: 7a3fb1b214b5
Create Date: 2017-08-02 21:36:30.411735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26f0e3434ae'
down_revision = '7a3fb1b214b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_brand', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_brand', 'fp_site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fp_brand', type_='foreignkey')
    op.drop_column('fp_brand', 'site_id')
    # ### end Alembic commands ###
