"""add category path

Revision ID: c79be4d02313
Revises: 66bdd744e7e2
Create Date: 2017-05-31 17:18:02.519580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79be4d02313'
down_revision = '66bdd744e7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_category_path',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fp_category.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'path_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fp_category_path')
    # ### end Alembic commands ###
