"""modify category icon/cover

Revision ID: c9b4676adb67
Revises: 5df72bf7d9fa
Create Date: 2017-05-29 12:23:10.313077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9b4676adb67'
down_revision = '5df72bf7d9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_category', sa.Column('cover_id', sa.Integer(), nullable=True))
    op.add_column('fp_category', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.drop_column('fp_category', 'icon')
    op.drop_column('fp_category', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_category', sa.Column('image', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('fp_category', sa.Column('icon', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('fp_category', 'icon_id')
    op.drop_column('fp_category', 'cover_id')
    # ### end Alembic commands ###
