"""add site_id for product table

Revision ID: ddddc91d3323
Revises: 993deebe4fd5
Create Date: 2017-08-03 16:34:36.650646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddddc91d3323'
down_revision = '993deebe4fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_product', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fp_product', 'fp_site', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fp_product', type_='foreignkey')
    op.drop_column('fp_product', 'site_id')
    # ### end Alembic commands ###
