"""add locale for user table

Revision ID: ea8db3b6c178
Revises: 0d5f8327248e
Create Date: 2017-07-27 23:47:42.786873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8db3b6c178'
down_revision = '0d5f8327248e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_user', sa.Column('locale', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_user', 'locale')
    # ### end Alembic commands ###
