"""add last_updated for currency

Revision ID: f701a9ea2ff9
Revises: 9398e136736e
Create Date: 2017-06-09 12:36:21.163653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f701a9ea2ff9'
down_revision = '9398e136736e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fp_currency', sa.Column('last_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fp_currency', 'last_updated')
    # ### end Alembic commands ###
